### ISSUE TITLE
Add keyboard support to move 2 axes

### ISSUE THREAD

**Issue by MrRemiB** [GoogleChromeLabs/rotavo#2]
Hi, 

My 2010 Canvas experiment was based on Keyboard inputs (AQ / PM) to turn buttons.
http://remi.bezeux.fr/projets/Telecran/

Could you implement it to move vertical / horizontal axes simultanely ?

**Comment by rowan-m** [comment]
Oh, forgot to mention - this should actually be there now.
[w, a, s, d] → left knob
[i, j, k, l] → right knob
